services:
  db:
    image: postgres:15-alpine
    container_name: uspolicyfeed-db
    restart: always
    environment:
      POSTGRES_USER: uspolicyfeed
      POSTGRES_PASSWORD: uspolicyfeed_pass_123
      POSTGRES_DB: uspolicyfeed
    ports:
      - '127.0.0.1:5436:5432'
    volumes:
      - uspolicyfeed_db_data:/var/lib/postgresql/data

volumes:
  uspolicyfeed_db_data:


